### PR TITLE
Add favicons #31

### PR DESCRIPTION
**Pull request by leee**

### CODE REVIEW

**Comment by leee** [comment]
Makes sense being too large. My read is crediting in readme is all that is necessary. Changing.

**Comment by r-pop** [comment]
I merged in more hospitals and there are conflicts now, could you resolve? Once the only changed lines in index.html are the header I will merge and deploy.

**Comment by leee** [comment]
(Commenting just in case you weren't getting notifications of the additional merges).

**Comment by leee** [comment]
Closing this in favor of #190.

**Pull request closed without merging**
